namespace DispenserProvider;

public enum Env
{
    PRODUCTION_MODE,
    SECRET_ID_OF_SIGN_ACCOUNT,
    SECRET_KEY_OF_SIGN_ACCOUNT,
    VALID_UNTIL_MAX_OFFSET_IN_SECONDS,
    COOLDOWN_OFFSET_IN_SECONDS,
    VALID_FROM_OFFSET_IN_SECONDS
}