namespace DispenserProvider;

public enum Env
{
    PRODUCTION_MODE,
    SECRET_ID_OF_SIGN_ACCOUNT,
    SECRET_KEY_OF_SIGN_ACCOUNT,
    VALID_UNTIL_MAX_OFFSET_IN_SECONDS,
    COOLDOWN_OFFSET_IN_SECONDS,
    VALID_FROM_OFFSET_IN_SECONDS,
    STRAPI_GRAPHQL_URL,
    STAGE_POSTGRES_HOSTNAME,
    STAGE_POSTGRES_PORT,
    STAGE_POSTGRES_DB_USER,
    STAGE_POSTGRES_DB_NAME,
    STAGE_POSTGRES_SSL_CERT_FULL_PATH,
    STAGE_POSTGRES_AWS_REGION,
    PROD_POSTGRES_HOSTNAME,
    PROD_POSTGRES_PORT,
    PROD_POSTGRES_DB_NAME,
    PROD_POSTGRES_SECRET_ID,
    PROD_POSTGRES_SECRET_KEY_OF_USERNAME,
    PROD_POSTGRES_SECRET_KEY_OF_PASSWORD,
    MULTI_CALL_CONTRACT_ADDRESS
}