namespace DispenserProvider;

public enum Env
{
    PRODUCTION_MODE,
    SECRET_ID_OF_SIGN_ACCOUNT,
    SECRET_KEY_OF_SIGN_ACCOUNT,
    VALID_UNTIL_MAX_OFFSET_IN_SECONDS,
    COOLDOWN_OFFSET_IN_SECONDS,
    VALID_FROM_OFFSET_IN_SECONDS,
    SECRET_NAME_OF_DISPENSER_CONNECTION,
    STRAPI_GRAPHQL_URL,
    STAGE_POSTGRES_HOSTNAME,
    STAGE_POSTGRES_PORT,
    STAGE_POSTGRES_DB_USER,
    STAGE_POSTGRES_DB_NAME,
    STAGE_POSTGRES_SSL_CERT_FULL_PATH,
    STAGE_POSTGRES_AWS_REGION,
    MULTI_CALL_CONTRACT_ADDRESS,
}