namespace DispenserProvider;

public enum ErrorCode
{
    INVALID_STAGE,
    INVALID_HANDLER_REQUEST,
    DISPENSER_NOT_FOUND,
    USERS_FOR_DELETE_NOT_FOUND,
    CHAIN_NOT_SUPPORTED,
    ASSET_ALREADY_WITHDRAWN,
    ASSET_ALREADY_REFUNDED,
    REFUND_TIME_IS_EXPIRED,
    SIGNATURE_NOT_FOUND,
    SIGNATURE_VALID_TIME_NOT_ARRIVED,
    SIGNATURE_VALID_TIME_IS_EXPIRED,
    SIGNATURE_TYPE_IS_INVALID,
    SIGNATURE_IS_STILL_VALID,
    SIGNATURE_GENERATION_VALID_TIME_NOT_ARRIVED
}