name: Deploy Lambda Function

on:
  release:
    types: [published]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_ACTOR: ${{ github.actor }}

jobs:
  deploy:
    if: ${{ github.event.release.target_commitish == 'master' }}
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: dotnet build --configuration Release

      - name: Install Amazon Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools
      
      - name: Package Lambda function
        run: dotnet lambda package --configuration Release --output-package deployment.zip

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-deployment
          path: deployment.zip

      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-deployment

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy Lambda Code
        env:
          LAMBDA_NAME: ${{ secrets.LAMBDA_NAME }}
        run: |
          aws lambda update-function-code --function-name "$LAMBDA_NAME" --zip-file fileb://deployment.zip

      - name: Update Lambda Description with Release URL
        env:
          LAMBDA_NAME: ${{ secrets.LAMBDA_NAME }}
          RELEASE_URL: ${{ github.event.release.html_url }}
        run: |
          aws lambda update-function-configuration --function-name "$LAMBDA_NAME" --description "$RELEASE_URL"
